---
#- name: Check if the remote file exists
#  stat:
#    path: "{{ upload_alexandria_path }}"
#  register: config_file_present

#- name: Upload config file
#  template:
#    src: alexandria-application.yml
#    dest: "{{ upload_alexandria_path }}"
#    force: yes

#- name: Rename config file
#  command: mv {{ upload_alexandria_path }}/alexandria-application.yml {{ upload_alexandria_path }}/application.yml
